server:
 port: 8090
 
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
   show-sql: true
   hiberate:
    ddl-auto: update
  h2:
   console:
     enable: true